"""Crear tabla mascotas

Revision ID: f646381f9de1
Revises: 
Create Date: 2026-03-16 15:11:36.321389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f646381f9de1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mascotas', sa.Column('peso', sa.Float(), nullable=False))
    op.alter_column('mascotas', 'nombre',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('mascotas', 'especie',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('mascotas', 'raza')
    op.drop_column('mascotas', 'fecha_ingreso')
    op.drop_column('mascotas', 'descripcion')
    op.drop_column('mascotas', 'edad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mascotas', sa.Column('edad', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mascotas', sa.Column('descripcion', mysql.TEXT(), nullable=True))
    op.add_column('mascotas', sa.Column('fecha_ingreso', sa.DATE(), nullable=True))
    op.add_column('mascotas', sa.Column('raza', mysql.VARCHAR(length=50), nullable=True))
    op.alter_column('mascotas', 'especie',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('mascotas', 'nombre',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('mascotas', 'peso')
    # ### end Alembic commands ###
